steps:
  - name: Hello World
    command: 'echo "Hello Probo pal. If you are reading this output you have your first successful Probo build step. Probo gives you a fresh environment for each build, so you can run whatever you want. This build step is using the default Probo build plugin: Shell."'
  - name: Install Drupal
    plugin: Drupal
    runInstall: true
    profileName: standard
    clearCaches: false
  - name: Run Behat tests
    command: 'cd /var/www/html/tests ; composer install ; ./bin/behat'
  - name: Hello Again
    command: 'echo "You can use Probo to run automated tests like the previous step did. Or not. Probo is useful with or without tests."'
  - name: Probo Hero
    command: 'echo "
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=======I+:::,,MMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM77======8:::::::,,,MMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM77777777777MMMMMMMMMMMMM777=====O::::::::::O,,,,MMMMMMMM
MMMMMMMMMMMMMMMMMMMMM7777777777777777777MMMM777778I,,,,8::::::::::::8,,,,,,MMMMM
MMMMMMMMMMMMMMMMMMMMMMMM7$7777777777777777777777,,,,,,,,:::::::::::::,,,,,,MMMMM
MMMMMMMMMMMMMMMMMMMMMMMM77$777777777777777777777,,,,,,,,,::::::::::~..8,,,,,MMMM
MMMMMMMMMMMMMMMMMMMMMMMM77$$77777$$$77777777777777,,,,,,,8:::::::8......8,,,~7MM
MMMMMMMMMMMMMMMMMMMMMMM77$$$$$$$$$77$$$$$77777777777~,,,,,+::::?...........,,77M
MMMMMMMMMMMMMMMM77777777$77777777777777777777777777777,,,,,:I................~7M
MMMMMMMMMMMMMM777777777777777777777777777777777777777788O++:8.................7M
MMMMMMMMMMMMM777777777777777777777777777777?????8++++77++++:::~.............::7M
MMMMMMMMMMMM7777777777777777777777777777????????++++++++++8::::::8.......8:::7+M
MMMMMMMMMMMM7777777777777777777777777M++++++????++++++++++::::::::::+..8:::::++M
MMMMMMMMMMM77777777777777777$$77777MM++++++M???8++++++++++:::::::::::::::::::++M
MMMMMMMMMM77$$$77777777$$$$$77777MMM+++++MMMM??I+++++++++8:::::::::::8::::::=+MM
MMMMMMMMM777$$$$$$$$$$$$$$$7777MMMMM++++++++++?++++++++++:::::::::::::::::::+MMM
MMMMMM77777$$$$$$$$$$$$$$77777MMMMMMMMMMMMMMM++++++++++78:::::::::::?:::::::MMMM
77777777$$$$$$$$$$$$$$$$7777MMMMMMMMMMMMMMMM+++8887777777778::::::::8:::::+++MMM
MM777$$$$$$$$$$$$$$$$$$7777MMMMMMMMMMMMMMMMM++MMM7777777I77778::::::::::MMM++MMM
MMMMM777$$$$$$$$$$$$$77777MMMMMMMMMMMMMMMMMMMMMMMMM7777III777777?::=::IMMMMMMMMM
MMMMMMMM7777$$$$$$$77777MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIII777777778$IIIMMMMMMMMM
MMMMMMMMMMMM7777777777MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIII777MMMMMMMIIIMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIIMMMMMMMMMMMIIIIMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIIMMMMMMMMMMMMIIIMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIMMMMMMMMMMMMMIIIMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIMMMMMMMMMMMMMMIIMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIMMMMMMMMMMMMMMMIIMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIMMMMMMMMMMMMMMMMIMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIMMMMMMMMMMMMMMMMMMIMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIMMMMM"'
